baseURL = "/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "ja"
paginate = 5
rssLimit = 10
theme = "hugo-texify3"
title = "Xlog"
googleAnalytics = "G-KS3MY4GBG7"

[author]
name = "Buntin Synthia"
email = "mail@buntin.xyz"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
pre = """
<svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M17,11H16a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm0,4H16a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2ZM11,9h6a1,1,0,0,0,0-2H11a1,1,0,0,0,0,2ZM21,3H7A1,1,0,0,0,6,4V7H3A1,1,0,0,0,2,8V18a3,3,0,0,0,3,3H18a4,4,0,0,0,4-4V4A1,1,0,0,0,21,3ZM6,18a1,1,0,0,1-2,0V9H6Zm14-1a2,2,0,0,1-2,2H7.82A3,3,0,0,0,8,18V5H20Zm-9-4h1a1,1,0,0,0,0-2H11a1,1,0,0,0,0,2Zm0,4h1a1,1,0,0,0,0-2H11a1,1,0,0,0,0,2Z"/>
</svg>
"""
weight = 1

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
pre = """
<svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M2.88,16.88a3,3,0,0,0,0,4.24,3,3,0,0,0,4.24,0,3,3,0,0,0-4.24-4.24Zm2.83,2.83a1,1,0,0,1-1.42-1.42,1,1,0,0,1,1.42,0A1,1,0,0,1,5.71,19.71ZM5,12a1,1,0,0,0,0,2,5,5,0,0,1,5,5,1,1,0,0,0,2,0,7,7,0,0,0-7-7ZM5,8a1,1,0,0,0,0,2,9,9,0,0,1,9,9,1,1,0,0,0,2,0,11.08,11.08,0,0,0-3.22-7.78A11.08,11.08,0,0,0,5,8Zm10.61.39A15.11,15.11,0,0,0,5,4,1,1,0,0,0,5,6,13,13,0,0,1,18,19a1,1,0,0,0,2,0A15.11,15.11,0,0,0,15.61,8.39Z"/>
</svg>
"""
weight = 2

[[menu.main]]
identifier = "about"
name = "ABOUT"
url = "/about"
pre = """
<img width="24" height="24" src="https://img.icons8.com/external-tal-revivo-color-tal-revivo/96/external-cloudflare-provides-content-delivery-network-services-ddos-mitigation-logo-color-tal-revivo.png" alt="external-cloudflare-provides-content-delivery-network-services-ddos-mitigation-logo-color-tal-revivo"/>
"""
weight = 3


[taxonomies]
tags = "tags"
categories = "categories"

[params]
title = "xlog"
description = "xlog buntin notes"
footnote = """
Powered by  <a class=link href=https://www.xlog.systems target=_blank rel=noopener>XLog</a> | 
Theme <a class=link href=https://github.com/BuntinJP/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = ["js/cloudflare_analytics.js"]
dateFormat = "2006-01-02"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true


[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
    data-repo="BuntinJP/xlog"
    data-repo-id="R_kgDOLWCm7A"
    data-category="General"
    data-category-id="DIC_kwDOLWCm7M4CdhoJ"
    data-mapping="pathname"
    data-strict="1"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="ja"
    crossorigin="anonymous"
    async>
</script>
"""

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" 
    data-cfasync="false" 
    src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
    data-id="buntin" data-description="Support me on Buy me a coffee!" 
    data-message="金plz" 
    data-color="#5F7FFF" 
    data-position="Right" 
    data-x_margin="18" 
    data-y_margin="18">
</script>
"""

[params.sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true
