import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, extname, join, parse } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { parseBlogFrontmatter } from '../src/lib/blog-frontmatter';
import { renderSocialImage } from '../src/lib/social-image';
import {
  articleSocialImagePath,
  siteSocialImagePath,
} from '../src/lib/social-image-config';

type PostCopy = Readonly<{
  categories: readonly string[];
  description: string;
  lastModifiedAt: string;
  slug: string;
  tags: readonly string[];
  title: string;
}>;

const outputRoot = join(process.cwd(), 'public', 'generated', 'social-images');
const manifestPath = join(process.cwd(), 'src', 'generated', 'social-image-paths.ts');
const publicCacheManifestPath = join(
  process.cwd(),
  'src',
  'generated',
  'public-cache-paths.ts',
);

const fail = (message: string): never => {
  throw new Error(`[social-images] ${message}`);
};

const frontmatter = (source: string, filename: string): string => {
  const match = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(source);
  return match?.[1] ?? fail(`${filename}: YAML frontmatter is missing or malformed`);
};

const parseFrontmatter = (source: string, filename: string) => {
  try {
    const value: unknown = parseYaml(frontmatter(source, filename));
    return parseBlogFrontmatter(value, filename);
  } catch (error: unknown) {
    return fail(`${filename}: ${error instanceof Error ? error.message : String(error)}`);
  }
};

const outputPath = (publicPath: string): string => {
  const prefix = '/generated/social-images/';
  if (!publicPath.startsWith(prefix)) return fail(`unexpected public path: ${publicPath}`);
  return join(process.cwd(), 'public', ...publicPath.slice(1).split('/'));
};

const writeSocialImage = async (path: string, copy: Readonly<{ description?: string; title: string }>) => {
  const response = await renderSocialImage(copy);
  if (!response.ok) fail(`${path}: renderer returned HTTP ${String(response.status)}`);

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, new Uint8Array(await response.arrayBuffer()));
};

const readPublishedPosts = async (): Promise<readonly PostCopy[]> => {
  const contentDirectory = join(process.cwd(), 'content', 'blog');
  const filenames = (await readdir(contentDirectory))
    .filter((filename) => extname(filename) === '.mdx' && filename !== 'index.mdx')
    .toSorted();

  const posts = await Promise.all(
    filenames.map(async (filename): Promise<PostCopy | undefined> => {
      const source = await readFile(join(contentDirectory, filename), 'utf8');
      const data = parseFrontmatter(source, filename);
      if (data.draft) return undefined;

      const slug = parse(filename).name;
      if (!/^[a-z0-9][a-z0-9._-]*$/.test(slug)) return fail(`${filename}: unsupported URL slug`);

      return {
        categories: data.categories,
        slug,
        tags: data.tags,
        title: data.title,
        description: data.description,
        lastModifiedAt: data.updatedAt ?? data.publishedAt,
      };
    }),
  );

  return posts.filter((post): post is PostCopy => post !== undefined);
};

const writePathManifest = async (paths: readonly string[]): Promise<void> => {
  const source = [
    '// Generated by scripts/generate-social-images.ts. Do not edit manually.',
    'export const generatedArticleSocialImagePaths = [',
    ...paths.toSorted().map((path) => `  '${path}',`),
    '] as const;',
    '',
  ].join('\n');

  await mkdir(dirname(manifestPath), { recursive: true });
  await writeFile(manifestPath, source);
};

const writePublicCacheManifest = async (posts: readonly PostCopy[]): Promise<number> => {
  const categoryNames = new Set(posts.flatMap(({ categories }) => categories));
  const tagNames = new Set(posts.flatMap(({ tags }) => tags));
  const paths = Array.from(
    new Set([
      '/',
      '/posts',
      '/categories',
      '/tags',
      ...posts.map(({ slug }) => `/posts/${slug}`),
      ...Array.from(categoryNames, (name) => `/categories/${encodeURIComponent(name)}`),
      ...Array.from(tagNames, (name) => `/tags/${encodeURIComponent(name)}`),
    ]),
  ).toSorted();
  const source = [
    '// Generated by scripts/generate-social-images.ts. Do not edit manually.',
    'const publicCacheablePathnames = new Set<string>([',
    ...paths.map((path) => `  ${JSON.stringify(path)},`),
    ']);',
    '',
    'const normalizePathname = (pathname: string): string | undefined => {',
    '  try {',
    "    const withoutTrailingSlash = pathname.length > 1 ? pathname.replace(/\\/$/, '') : pathname;",
    '    return withoutTrailingSlash',
    "      .split('/')",
    '      .map((segment) => encodeURIComponent(decodeURIComponent(segment)))',
    "      .join('/');",
    '  } catch {',
    '    return undefined;',
    '  }',
    '};',
    '',
    'export const isPublicCacheablePathname = (pathname: string): boolean => {',
    '  const normalized = normalizePathname(pathname);',
    '  return normalized !== undefined && publicCacheablePathnames.has(normalized);',
    '};',
    '',
  ].join('\n');

  await mkdir(dirname(publicCacheManifestPath), { recursive: true });
  await writeFile(publicCacheManifestPath, source);
  return paths.length;
};

const main = async (): Promise<void> => {
  const posts = await readPublishedPosts();
  const articlePaths = posts.map((post) => articleSocialImagePath(post.slug, post.lastModifiedAt));
  await rm(outputRoot, { recursive: true, force: true });
  await writePathManifest(articlePaths);
  const publicCachePathCount = await writePublicCacheManifest(posts);

  await Promise.all([
    writeSocialImage(outputPath(siteSocialImagePath), { title: 'xlog.systems' }),
    ...posts.map((post, index) =>
      writeSocialImage(outputPath(articlePaths[index] ?? fail(`missing path for ${post.slug}`)), {
        title: post.title,
        description: post.description,
      }),
    ),
  ]);

  console.log(
    `[social-images] generated ${String(posts.length + 1)} static PNG files and ${String(publicCachePathCount)} cacheable page paths`,
  );
};

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
